start: §eStarting server...
#Debug mode, if disabled, then some of the stack traces won't be visible in console.
debug: -
#Servers default language.
defaultLang: en
#EconomyAPI settings
economy:
  balanceTypes:
    default:
      name: default
      suffix: $
      defaultValue: 100
#Migrate all the Economy data through Vault from an other Economy plugin, i.e. Essentials.
  migrate: -
#The type of SpigotLibs vault hook, available options:
#NONE - do NOT hook to Vault at all (not suggested)
#USER - hook to Vault as an Economy user (suggested if you don't want to use SpigotLibs Economy management)
#PROVIDER - hook to Vault as an Economy provider (override other Economy plugins, like Essentials)
  vaultHookType: USER
#Enable / disable packet events which costs some performance, but gives
#ability for developers to catch packets and code awesome plugin features :)
packetAPI: -
#Hook to the clips PlaceholderAPI in order to obtain more variables.
phaHook: +
#PlayerFile settings
playerFile:
  backend: FILE
  file: players.yml
  mysql:
    table: SpigotLib
    host: 127.0.0.1
    username: root
    password: root
    database: SpigotLib
    timeout: 10000
#BungeeAPI
bungee:
  playerCount: 100
  playerList: 100
  servers: 1000000
  currentServerName: 1000000
  uuidAll: 1000000
  serverIP: 1000000
  ipOnJoin: +
  uuidOnJoin: +
#Allows sync and async metrics of the truth server tps, for the <tps>
#variable, it also helps to detect informations about possible server crashes.
tpsMeter:
  checkTime: 10000
  limit: 15