#Servers default language.
defaultLang: en
#Tab completion will need the tab.complete perm.
tabCompletePerm: +
#Hook to the clips PlaceholderAPI in order to obtain more variables.
phaHook: +
debug: -
backup: plugins/SpigotLib/backups/config-backup(<time>).yml
tpsMeter:
  limit: 5
  checkTime: 10000
  startupDelay: 35000
connectionLog:
  enabled: +
  #You can blacklist here some ips, which you would not like to see in the log.
  blacklist:
  - 0.0.0.0
  ping: [ConnectionLog] Player <name>(<uuid>), tried to ping to the server from ip <ip>.
  pingmore: [ConnectionLog] One of the following players tried to ping to the server from ip <ip>:
  pingunknown: [ConnectionLog] Unknown player tried to ping to the server from ip <ip>.
  loginunknown: [ConnectionLog] Unknown player tried to login to the server from ip <ip>.
  login: [ConnectionLog] Player <name>(<uuid>), tried to login to the server from ip <ip>.
  loginmore: [ConnectionLog] One of the following players tried to login to the server from ip <ip>:
  ipUUIDBase:
#Chat settings.
chat:
  #Enable SpigotLib chat management.
  enabled: +
  #List here all the color codes, that should be replaced, if the player has chat.color.<colorcode> perm.
  colors: 0123456789abcdefklmnor
  #The prefix before colorcodes.
  colorPrefix: &
  #Set the new line character, set it to empty for disabling this feature.
  #You need the chat.multiline permission for using this character.
  newLineCharacter: \\n
  #Allow writing empty lines with more then one, newline characters, if you have the chat.emptyLines permission.
  allowEmptyLines: +
  #Configuration for long messages.
  longMessage:
    #Enable using this feature, if you have chat.longer perm.
    enabled: +
    #If you write more, than the bellow set amount of characters, your message will be puffered, if not, your whole message will be sent.
    pufferAfter: 90
    #Limit maximum length of longer messages, per permissionly (chat.longerlimit.<group> permissions)
    lengthLimit:
      player: 150
      ranked: 300
      admin: 500
antiSignHack:
  enabled: +
  limit: 50
antiItemHack:
  enabled: -
  helmets: 86,298,302,306,310,314,397
  chestplates: 299,303,307,311,315
  leggings: 300,304,308,312,316
  boots: 301,305,309,313,317
  whitelist:
  - 1
  - 1:1
  - 1:2
  - 1:3
  - 1:4
  - 1:5
  - 1:6
  - 2
  - 3
  - 3:1
  - 3:2
  - 4
  - 5
  - 5:1
  - 5:2
  - 5:3
  - 5:4
  - 5:5
  - 6
  - 6:1
  - 6:2
  - 6:3
  - 6:4
  - 6:5
  - 7
  - 12
  - 12:1
  - 13
  - 14
  - 15
  - 16
  - 17
  - 17:1
  - 17:2
  - 17:3
  - 18
  - 18:1
  - 18:2
  - 18:3
  - 19
  - 19:1
  - 20
  - 21
  - 22
  - 23
  - 24
  - 24:1
  - 24:2
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 31:1
  - 31:2
  - 32
  - 33
  - 35
  - 35:1
  - 35:2
  - 35:3
  - 35:4
  - 35:5
  - 35:6
  - 35:7
  - 35:8
  - 35:9
  - 35:10
  - 35:11
  - 35:12
  - 35:13
  - 35:14
  - 35:15
  - 37
  - 38
  - 38:1
  - 38:2
  - 38:3
  - 38:4
  - 38:5
  - 38:6
  - 38:7
  - 38:8
  - 39
  - 40
  - 41
  - 42
  - 44
  - 44:1
  - 44:2
  - 44:3
  - 44:4
  - 44:5
  - 44:6
  - 44:7
  - 45
  - 46
  - 47
  - 48
  - 49
  - 50
  - 53
  - 54
  - 56
  - 57
  - 58
  - 61
  - 64
  - 65
  - 66
  - 67
  - 68
  - 69
  - 70
  - 71
  - 72
  - 73
  - 76
  - 77
  - 78
  - 79
  - 80
  - 81
  - 82
  - 83
  - 84
  - 85
  - 86
  - 87
  - 88
  - 89
  - 90
  - 91
  - 92
  - 95
  - 95:1
  - 95:2
  - 95:3
  - 95:4
  - 95:5
  - 95:6
  - 95:7
  - 95:8
  - 95:9
  - 95:10
  - 95:11
  - 95:12
  - 95:13
  - 95:14
  - 95:15
  - 96
  - 97
  - 97:1
  - 97:2
  - 97:3
  - 97:4
  - 97:5
  - 98
  - 98:1
  - 98:2
  - 98:3
  - 99
  - 100
  - 101
  - 102
  - 103
  - 106
  - 107
  - 108
  - 109
  - 110
  - 111
  - 112
  - 113
  - 114
  - 115
  - 116
  - 117
  - 118
  - 120
  - 121
  - 123
  - 125
  - 125:1
  - 125:2
  - 125:3
  - 125:4
  - 125:5
  - 126
  - 126:1
  - 126:2
  - 126:3
  - 126:4
  - 126:5
  - 128
  - 129
  - 130
  - 131
  - 132
  - 133
  - 134
  - 135
  - 136
  - 138
  - 139
  - 139:1
  - 140
  - 143
  - 144
  - 145
  - 146
  - 147
  - 148
  - 149
  - 151
  - 152
  - 153
  - 154
  - 155
  - 155:1
  - 155:2
  - 156
  - 157
  - 158
  - 159
  - 159:1
  - 159:2
  - 159:3
  - 159:4
  - 159:5
  - 159:6
  - 159:7
  - 159:8
  - 159:9
  - 159:10
  - 159:11
  - 159:12
  - 159:13
  - 159:14
  - 159:15
  - 160
  - 160:1
  - 160:2
  - 160:3
  - 160:4
  - 160:5
  - 160:6
  - 160:7
  - 160:8
  - 160:9
  - 160:10
  - 160:11
  - 160:12
  - 160:13
  - 160:14
  - 160:15
  - 161
  - 161:1
  - 162
  - 162:1
  - 163
  - 164
  - 165
  - 166
  - 167
  - 168
  - 168:1
  - 168:2
  - 169
  - 170
  - 171
  - 171:1
  - 171:2
  - 171:3
  - 171:4
  - 171:5
  - 171:6
  - 171:7
  - 171:8
  - 171:9
  - 171:10
  - 171:11
  - 171:12
  - 171:13
  - 171:14
  - 171:15
  - 172
  - 173
  - 174
  - 175
  - 175:1
  - 175:2
  - 175:3
  - 175:4
  - 175:5
  - 176
  - 177
  - 179
  - 179:1
  - 179:2
  - 180
  - 181
  - 182
  - 183
  - 184
  - 185
  - 186
  - 187
  - 188
  - 189
  - 190
  - 191
  - 192
  - 193
  - 194
  - 195
  - 196
  - 197
  - 256
  - 257
  - 258
  - 259
  - 260
  - 261
  - 262
  - 263
  - 263:1
  - 264
  - 265
  - 266
  - 267
  - 268
  - 269
  - 270
  - 271
  - 272
  - 273
  - 274
  - 275
  - 276
  - 277
  - 278
  - 279
  - 280
  - 281
  - 282
  - 283
  - 284
  - 285
  - 286
  - 287
  - 288
  - 289
  - 290
  - 291
  - 292
  - 293
  - 294
  - 295
  - 296
  - 297
  - 298
  - 299
  - 300
  - 301
  - 302
  - 303
  - 304
  - 305
  - 306
  - 307
  - 308
  - 309
  - 310
  - 311
  - 312
  - 313
  - 314
  - 315
  - 316
  - 317
  - 318
  - 319
  - 320
  - 321
  - 322
  - 322:1
  - 323
  - 324
  - 325
  - 326
  - 327
  - 328
  - 329
  - 330
  - 331
  - 332
  - 333
  - 334
  - 335
  - 336
  - 337
  - 338
  - 339
  - 340
  - 341
  - 342
  - 343
  - 344
  - 345
  - 346
  - 347
  - 348
  - 349
  - 349:1
  - 349:2
  - 349:3
  - 350
  - 350:1
  - 351
  - 351:1
  - 351:2
  - 351:3
  - 351:4
  - 351:5
  - 351:6
  - 351:7
  - 351:8
  - 351:9
  - 351:10
  - 351:11
  - 351:12
  - 351:13
  - 351:14
  - 351:15
  - 352
  - 353
  - 354
  - 355
  - 356
  - 357
  - 358
  - 359
  - 360
  - 361
  - 362
  - 363
  - 364
  - 365
  - 366
  - 367
  - 368
  - 369
  - 370
  - 371
  - 372
  - 373
  - 374
  - 375
  - 376
  - 377
  - 378
  - 379
  - 380
  - 381
  - 382
  - 383:50
  - 383:51
  - 383:52
  - 383:54
  - 383:55
  - 383:56
  - 383:57
  - 383:58
  - 383:59
  - 383:60
  - 383:61
  - 383:62
  - 383:65
  - 383:66
  - 383:67
  - 383:68
  - 383:90
  - 383:91
  - 383:92
  - 383:93
  - 383:94
  - 383:95
  - 383:96
  - 383:98
  - 383:100
  - 383:101
  - 383:120
  - 384
  - 385
  - 386
  - 387
  - 388
  - 389
  - 390
  - 391
  - 392
  - 393
  - 394
  - 395
  - 396
  - 397
  - 397:1
  - 397:2
  - 397:3
  - 397:4
  - 398
  - 399
  - 400
  - 401
  - 402
  - 403 +ARROW_DAMAGE:1
  - 403 +ARROW_DAMAGE:2
  - 403 +ARROW_DAMAGE:3
  - 403 +ARROW_DAMAGE:4
  - 403 +ARROW_DAMAGE:5
  - 403 +ARROW_FIRE:1
  - 403 +ARROW_INFINITE:1
  - 403 +ARROW_KNOCKBACK:1
  - 403 +ARROW_KNOCKBACK:2
  - 403 +DAMAGE_ALL:1
  - 403 +DAMAGE_ALL:2
  - 403 +DAMAGE_ALL:3
  - 403 +DAMAGE_ALL:4
  - 403 +DAMAGE_ALL:5
  - 403 +DAMAGE_ARTHROPODS:1
  - 403 +DAMAGE_ARTHROPODS:2
  - 403 +DAMAGE_ARTHROPODS:3
  - 403 +DAMAGE_ARTHROPODS:4
  - 403 +DAMAGE_ARTHROPODS:5
  - 403 +DAMAGE_UNDEAD:1
  - 403 +DAMAGE_UNDEAD:2
  - 403 +DAMAGE_UNDEAD:3
  - 403 +DAMAGE_UNDEAD:4
  - 403 +DAMAGE_UNDEAD:5
  - 403 +DEPTH_STRIDER:1
  - 403 +DEPTH_STRIDER:2
  - 403 +DEPTH_STRIDER:3
  - 403 +DIG_SPEED:1
  - 403 +DIG_SPEED:2
  - 403 +DIG_SPEED:3
  - 403 +DIG_SPEED:4
  - 403 +DIG_SPEED:5
  - 403 +DURABILITY:1
  - 403 +DURABILITY:2
  - 403 +DURABILITY:3
  - 403 +FIRE_ASPECT:1
  - 403 +FIRE_ASPECT:2
  - 403 +KNOCKBACK:1
  - 403 +KNOCKBACK:2
  - 403 +LOOT_BONUS_BLOCKS:1
  - 403 +LOOT_BONUS_BLOCKS:2
  - 403 +LOOT_BONUS_BLOCKS:3
  - 403 +LOOT_BONUS_MOBS:1
  - 403 +LOOT_BONUS_MOBS:2
  - 403 +LOOT_BONUS_MOBS:3
  - 403 +LUCK:1
  - 403 +LUCK:2
  - 403 +LUCK:3
  - 403 +LURE:1
  - 403 +LURE:2
  - 403 +LURE:3
  - 403 +OXYGEN:1
  - 403 +OXYGEN:2
  - 403 +OXYGEN:3
  - 403 +PROTECTION_ENVIRONMENTAL:1
  - 403 +PROTECTION_ENVIRONMENTAL:2
  - 403 +PROTECTION_ENVIRONMENTAL:3
  - 403 +PROTECTION_ENVIRONMENTAL:4
  - 403 +PROTECTION_EXPLOSIONS:1
  - 403 +PROTECTION_EXPLOSIONS:2
  - 403 +PROTECTION_EXPLOSIONS:3
  - 403 +PROTECTION_EXPLOSIONS:4
  - 403 +PROTECTION_FALL:1
  - 403 +PROTECTION_FALL:2
  - 403 +PROTECTION_FALL:3
  - 403 +PROTECTION_FALL:4
  - 403 +PROTECTION_FIRE:1
  - 403 +PROTECTION_FIRE:2
  - 403 +PROTECTION_FIRE:3
  - 403 +PROTECTION_FIRE:4
  - 403 +PROTECTION_PROJECTILE:1
  - 403 +PROTECTION_PROJECTILE:2
  - 403 +PROTECTION_PROJECTILE:3
  - 403 +PROTECTION_PROJECTILE:4
  - 403 +SILK_TOUCH:1
  - 403 +THORNS:1
  - 403 +THORNS:2
  - 403 +THORNS:3
  - 403 +WATER_WORKER:1
  - 404
  - 405
  - 406
  - 407
  - 408
  - 409
  - 410
  - 411
  - 412
  - 413
  - 414
  - 415
  - 416
  - 417
  - 418
  - 419
  - 420
  - 421
  - 422
  - 423
  - 424
  - 425:15 hide:ATTRIBUTES hide:UNBREAKABLE hide:DESTROYS hide:PLACED_ON hide:POTION_EFFECTS color:WHITE
  - 425:14 hide:ATTRIBUTES hide:UNBREAKABLE hide:DESTROYS hide:PLACED_ON hide:POTION_EFFECTS color:ORANGE
  - 425:13 hide:ATTRIBUTES hide:UNBREAKABLE hide:DESTROYS hide:PLACED_ON hide:POTION_EFFECTS color:MAGENTA
  - 425:12 hide:ATTRIBUTES hide:UNBREAKABLE hide:DESTROYS hide:PLACED_ON hide:POTION_EFFECTS color:LIGHT_BLUE
  - 425:11 hide:ATTRIBUTES hide:UNBREAKABLE hide:DESTROYS hide:PLACED_ON hide:POTION_EFFECTS color:YELLOW
  - 425:10 hide:ATTRIBUTES hide:UNBREAKABLE hide:DESTROYS hide:PLACED_ON hide:POTION_EFFECTS color:LIME
  - 425:9 hide:ATTRIBUTES hide:UNBREAKABLE hide:DESTROYS hide:PLACED_ON hide:POTION_EFFECTS color:PINK
  - 425:8 hide:ATTRIBUTES hide:UNBREAKABLE hide:DESTROYS hide:PLACED_ON hide:POTION_EFFECTS color:GRAY
  - 425:7 hide:ATTRIBUTES hide:UNBREAKABLE hide:DESTROYS hide:PLACED_ON hide:POTION_EFFECTS color:SILVER
  - 425:6 hide:ATTRIBUTES hide:UNBREAKABLE hide:DESTROYS hide:PLACED_ON hide:POTION_EFFECTS color:CYAN
  - 425:5 hide:ATTRIBUTES hide:UNBREAKABLE hide:DESTROYS hide:PLACED_ON hide:POTION_EFFECTS color:PURPLE
  - 425:4 hide:ATTRIBUTES hide:UNBREAKABLE hide:DESTROYS hide:PLACED_ON hide:POTION_EFFECTS color:BLUE
  - 425:3 hide:ATTRIBUTES hide:UNBREAKABLE hide:DESTROYS hide:PLACED_ON hide:POTION_EFFECTS color:BROWN
  - 425:2 hide:ATTRIBUTES hide:UNBREAKABLE hide:DESTROYS hide:PLACED_ON hide:POTION_EFFECTS color:GREEN
  - 425:1 hide:ATTRIBUTES hide:UNBREAKABLE hide:DESTROYS hide:PLACED_ON hide:POTION_EFFECTS color:RED
  - 425 hide:ATTRIBUTES hide:UNBREAKABLE hide:DESTROYS hide:PLACED_ON hide:POTION_EFFECTS color:BLACK
  - 425:15 color:WHITE
  - 425:14 color:ORANGE
  - 425:13 color:MAGENTA
  - 425:12 color:LIGHT_BLUE
  - 425:11 color:YELLOW
  - 425:10 color:LIME
  - 425:9 color:PINK
  - 425:8 color:GRAY
  - 425:7 color:SILVER
  - 425:6 color:CYAN
  - 425:5 color:PURPLE
  - 425:4 color:BLUE
  - 425:3 color:BROWN
  - 425:2 color:GREEN
  - 425:1 color:RED
  - 425 color:BLACK
  - 427
  - 428
  - 429
  - 430
  - 431
  - 2256
  - 2257
  - 2258
  - 2259
  - 2260
  - 2261
  - 2262
  - 2263
  - 2264
  - 2265
  - 2266
  - 2267
economy:
  vaultHook: +
  liveSync: +
  balanceTypes:
    default:
      prefix:
      defaultValue: 100
      name: default
      suffix: $
packetMapping:
  v1_8_R2:
    PacketPlayInPosition: PacketPlayInFlying$PacketPlayInPosition
    PacketPlayInRelPositionLook: PacketPlayInFlying$PacketPlayInPositionLook
    PacketPlayInLook: PacketPlayInFlying$PacketPlayInLook
    PacketPlayOutRelEntityMove: PacketPlayOutEntity$PacketPlayOutRelEntityMove
    PacketPlayOutRelEntityMoveLook: PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook
    PacketPlayOutEntityLook: PacketPlayOutEntity$PacketPlayOutEntityLook
    ChatSerializer: IChatBaseComponent$ChatSerializer
  v1_8_R3:
    PacketPlayInPosition: PacketPlayInFlying$PacketPlayInPosition
    PacketPlayInRelPositionLook: PacketPlayInFlying$PacketPlayInPositionLook
    PacketPlayInLook: PacketPlayInFlying$PacketPlayInLook
    PacketPlayOutRelEntityMove: PacketPlayOutEntity$PacketPlayOutRelEntityMove
    PacketPlayOutRelEntityMoveLook: PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook
    PacketPlayOutEntityLook: PacketPlayOutEntity$PacketPlayOutEntityLook
    ChatSerializer: IChatBaseComponent$ChatSerializer
  v1_8_R4:
    PacketPlayInPosition: PacketPlayInFlying$PacketPlayInPosition
    PacketPlayInRelPositionLook: PacketPlayInFlying$PacketPlayInPositionLook
    PacketPlayInLook: PacketPlayInFlying$PacketPlayInLook
    PacketPlayOutRelEntityMove: PacketPlayOutEntity$PacketPlayOutRelEntityMove
    PacketPlayOutRelEntityMoveLook: PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook
    PacketPlayOutEntityLook: PacketPlayOutEntity$PacketPlayOutEntityLook
    ChatSerializer: IChatBaseComponent$ChatSerializer