bungee:
  fullyDisabled: +
  currentServerName: 1000000
  ipOnJoin: -
  playerCount: 100
  playerList: -1
  serverIP: -1
  servers: 1000000
  uuidAll: -1
  uuidOnJoin: -
debug: -
defaultLang: en
disableWeatherChange: -
economy: 
  balanceTypes: 
    default: 
      defaultValue: 100
      name: default
      suffix: $
  migrate: -
  vaultHookType: USER
packetAPI: -
phaHook: +
playerFile: 
  backend: FILE
  file: players.yml
  mysql: 
    database: SpigotLib
    host: 127.0.0.1
    password: root
    table: PlayerData
    timeout: 10000
    username: root
skinAPI: -
start: §eStarting server...
tpsMeter: 
  checkTime: 10000
  limit: 15