name: SpigotLib
main: gyurix.spigotlib.Main
author: gyuriX
version: 4.0DEV
loadbefore: [ProtocolLib]
softdepend: [ProtocolSupport,ViaVersion,Vault,Essentials,PlaceholderAPI]
commands:
  spigotlib:
    description: Main command
    aliases: [sl]
  lang:
    description: Basic player language selection command
    aliases: [lng]
