author: gyuriX
commands:
  spigotlib: 
    aliases: [sl]
    description: Main command
loadbefore: [ProtocolLib]
main: gyurix.spigotlib.Main
name: SpigotLib
softdepend: [ProtocolSupport,ViaVersion,Vault,Essentials,PlaceholderAPI,WorldEdit]
version: 6.0