name: SpigotLib
author: gyuriX
version: 6.0
main: gyurix.spigotlib.Main
loadbefore: [ProtocolLib]
softdepend: [ProtocolSupport,ViaVersion,Vault,Essentials,PlaceholderAPI,WorldEdit]
commands:
  spigotlib:
    aliases: [sl]
    description: Main command