name: SpigotLib
author: gyuriX
version: 6.3
main: gyurix.spigotlib.Main
loadbefore: [ProtocolLib]
softdepend: [LilyPad-Connect,ProtocolSupport,ViaVersion,Vault,Essentials,PlaceholderAPI,WorldEdit]
commands:
  spigotlib:
    aliases: [sl]
    description: Main command