name: SpigotLib
author: gyuriX
version: 7.0.2
main: gyurix.spigotlib.Main
loadbefore: [ProtocolLib,ProtocolSupport]
softdepend: [LilyPad-Connect,ViaVersion,Vault,Essentials,PlaceholderAPI,WorldEdit]
commands:
  spigotlib:
    aliases: [sl]
    description: Main command